In [1]:
import pandas as pd


In [2]:
from pandas import Series, DataFrame

In [3]:
import pandas as pd
from pandas import Series, DataFrame

obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [3]:
import pandas as pd
from pandas import Series, DataFrame

obj2 = Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [4]:
obj2['a']

-5

In [5]:
obj2['d'] = 6

In [9]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
import numpy as np 
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [15]:
import pandas as pd
from pandas import Series, DataFrame

sdata = {'Ohio':35000, 'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
states = ['California', 'Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
obj3 +obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
obj4.name = 'population'

In [24]:
obj4.index.name = 'state'

In [25]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [26]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [27]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

<h1>Объект DataFrame<h1>

In [28]:
import pandas as pd
from pandas import Series, DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

In [29]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [30]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [31]:
pd.DataFrame(data, columns=['year','state', 'pop'] )

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [32]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                      index=['one','two','three','four',
                             'five','six'])

In [33]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [34]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [35]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [36]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [37]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [38]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [39]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [40]:
val = pd.Series([-1.2,-1.5,-1.7], index=['two', 'four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [41]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [42]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [44]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [45]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [46]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [47]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [48]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [49]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [50]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

<h1>Задание 1</h1>


Двумерный ndarray: Можно передать двумерный массив NumPy в качестве аргумента. Каждая строка массива будет представлена в виде отдельной строки в DataFrame, а каждый столбец - в виде отдельной колонки.

Словарь массивов, списков или кортежей: Можно передать словарь, где ключи будут использоваться в качестве названий колонок, а значения - в качестве данных в колонках.

Структурированный массив NumPy: Можно передать структурированный массив NumPy, где каждое поле будет представлено в виде отдельной колонки в DataFrame.

Словарь объектов Series: Можно передать словарь, где ключи будут использоваться в качестве названий колонок, а значения - в качестве данных в колонках. Значения должны быть объектами Series.

Словарь словарей: Можно передать словарь, где ключи первого уровня будут использоваться в качестве названий колонок, а значения - словарями, где ключи второго уровня будут использоваться в качестве индексов строк, а значения - в качестве данных.

Список словарей или объектов Series: Можно передать список, где каждый элемент будет представлять отдельную строку данных. Элементы могут быть словарями или объектами Series.

Список списков или кортежей: Можно передать список, где каждый элемент будет представлять отдельную строку данных. Элементы должны быть списками или кортежами.

Другой объект DataFrame: Можно передать другой объект DataFrame, чтобы создать его копию.

Объект Numpy MaskedArray: Можно передать объект Numpy MaskedArray, который представляет собой массив с маской значений.

In [51]:
import pandas as pd
import numpy as np

data = np.array([[1,2,3], [4,5,6], [7,8,9]])
df = pd.DataFrame(data, columns=['A','B','C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [52]:
import pandas as pd

data1 = {'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
df = DataFrame(data1)
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [53]:
import pandas as pd
import numpy as np 

data = np.array([(1, 'A', 0.5), (2, 'B', 0.7), (2, 'C', 0.9)], dtype=[('ID', int), ('Label', str), ('Value', float)])
df = pd.DataFrame(data)
df

ID Label  Value
0   1          0.5
1   2          0.7
2   2          0.9

In [54]:
import pandas as pd

data = {'A': pd.Series([1,2,3]), 'B': pd.Series([4,5,6]), 'C': pd.Series([7,8,9])}
df = pd.DataFrame(data)
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [55]:
import pandas as pd
import numpy as np

data = {'A':{'x':1, 'y':2}, 'B': {'x':3, 'y':4}, 'C':{'x':5, 'y':6}}
df = pd.DataFrame(data)
df

A  B  C
x  1  3  5
y  2  4  6

In [56]:
import pandas as pd

data = [{'A':1, 'B':4}, {'A':2, 'B':5}, {'A':3, 'B':6}]
df = pd.DataFrame(data)
df

A  B
0  1  4
1  2  5
2  3  6

In [57]:
import pandas as pd 

df1 = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]})
df2 = pd.DataFrame(df1)
df2

A  B
0  1  4
1  2  5
2  3  6

In [58]:
import pandas as pd 
import numpy as np
import numpy.ma as ma

data = ma.array([[1,2], [3, ma.masked]])
df = pd.DataFrame(data, columns = ['A', 'B'])
df

C:\XboxGames\lib\site-packages\numpy\ma\core.py:2829: UserWarning: Warning: converting a masked element to nan.
  _data = np.array(data, dtype=dtype, copy=copy,
C:\XboxGames\lib\site-packages\numpy\ma\core.py:2867: UserWarning: Warning: converting a masked element to nan.
  [getmaskarray(np.asanyarray(m, dtype=_data.dtype))


A    B
0  1.0  2.0
1  3.0  NaN

<h1>Индексные объекты</h1>

In [59]:
import pandas as pd
from pandas import Series, DataFrame

obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [60]:
index[1:]

Index(['b', 'c'], dtype='object')

In [61]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [62]:
import numpy as np

labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [66]:
obj5 = pd.Series([1.5, -2.5, 0], index=labels)
obj5

0    1.5
1   -2.5
2    0.0
dtype: float64

In [67]:
obj5.index is labels

True

In [64]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [68]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [70]:
'Ohio' in frame3.columns

True

In [71]:
2003 in frame3.index

False

In [72]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

<h1>Задание 2<h1>

In [74]:
idx = pd.Index([1,2,3])
idx.append(pd.Index([4]))

Int64Index([1, 2, 3, 4], dtype='int64')

In [76]:
idx1 = pd.Index([1,2,3,4,5])
idx2 = pd.Index([1,2,3,6,7])
idx1.difference(idx2)

Int64Index([4, 5], dtype='int64')

In [77]:
idx1.intersection(idx2)

Int64Index([1, 2, 3], dtype='int64')

In [78]:
idx1.union(idx2)

Int64Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [83]:
idx3 = pd.Index([1,2,3,5])
idx3.isin([1,2,4,5])

array([ True,  True, False,  True])

In [86]:
idx4 = pd.Index(['a','b','c','d'])
idx4.delete([1,2])

Index(['a', 'd'], dtype='object')

In [87]:
idx5 = pd.Index(['a','b','c','d'])
idx5.drop(['d'])

Index(['a', 'b', 'c'], dtype='object')

In [94]:
idx6 = pd.Index(['a','b','c','d'])

idx6.insert(3, 'cd')

Index(['a', 'b', 'c', 'cd', 'd'], dtype='object')

In [102]:
idx7 = pd.Index([1,2,3]).is_monotonic_increasing
idx7

True

In [106]:
idx8 = pd.Index([1,5,7,7])
idx8.is_unique

False

In [107]:
idx9 = pd.Index([1, 1, 2, 3, 3])
idx9.unique()


Int64Index([1, 2, 3], dtype='int64')