In [2]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
import numpy as np

x = np.random.randn(8)
y = np.random.randn(8)

In [7]:
x

array([ 0.75674145,  0.01490983, -1.50170551, -2.84162706,  2.38021827,
        0.09953473,  0.35396719,  0.27676996])

In [8]:
y

array([ 1.31352474,  2.01927305,  0.08071285, -0.44397827, -0.79531468,
       -1.48490325,  1.93097446,  0.71760203])

In [9]:
np.maximum(x,y)

array([ 1.31352474,  2.01927305,  0.08071285, -0.44397827,  2.38021827,
        0.09953473,  1.93097446,  0.71760203])

In [10]:
import numpy as np

arr = np.random.randn(7) * 5
arr

array([ 2.54007994,  0.89591695,  1.45008253,  2.72027579, -1.5785814 ,
       -3.4325776 , -0.44555863])

In [11]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.54007994,  0.89591695,  0.45008253,  0.72027579, -0.5785814 ,
       -0.4325776 , -0.44555863])

In [12]:
whole_part

array([ 2.,  0.,  1.,  2., -1., -3., -0.])

In [13]:
arr

array([ 2.54007994,  0.89591695,  1.45008253,  2.72027579, -1.5785814 ,
       -3.4325776 , -0.44555863])

In [14]:
np.sqrt(arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [15]:
np.sqrt(arr, arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [16]:
arr

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

<h2>Задание 1:</h2>

<h3>1:</h3>

abs(x): возвращает абсолютное значение числа x.

fabs(x): возвращает абсолютное значение числа с плавающей запятой x.

sqrt(x): возвращает квадратный корень числа x.

square(x): возвращает квадрат числа x.

exp(x): возвращает экспоненту числа x.

log(x): возвращает натуральный логарифм числа x.

log10(x): возвращает десятичный логарифм числа x.


log2(x): возвращает двоичный логарифм числа x.

log1p(x): возвращает натуральный логарифм (1 + x).

sign(x): возвращает знак числа x (-1, 0 или 1).

ceil(x): округляет число x до ближайшего большего целого.

floor(x): округляет число x до ближайшего меньшего целого.

rint(x): округляет число x до ближайшего целого, с половинными значениями округляется к ближайшему четному целому.

modf(x, y): возвращает дробную и целую части числа x в виде отдельных значений.

isnan(x): проверяет, является ли число x NaN (не число).

isfinite(x): проверяет, является ли число x конечным числом.

isinf(x): проверяет, является ли число x бесконечностью.

cos(x): возвращает косинус угла x (в радианах).

cosh(x): возвращает гиперболический косинус угла x.

sin(x): возвращает синус угла x (в радианах).

sinh(x): возвращает гиперболический синус угла x.

tan(x): возвращает тангенс угла x (в радианах).

tanh(x): возвращает гиперболический тангенс угла x.

arccos(x): возвращает арккосинус числа x (в радианах).

arccosh(x): возвращает гиперболический арккосинус числа x.

arcsin(x): возвращает арксинус числа x (в радианах).

arcsinh(x): возвращает гиперболический арксинус числа x.

arctan(x): возвращает арктангенс числа x (в радианах).

arctanh(x): возвращает гиперболический арктангенс числа x.

logical_not(x): выполняет логическую операцию "НЕ" над значением или массивом значений.

In [19]:
np.abs(arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [20]:
np.fabs(arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [21]:
np.sqrt(arr)

array([1.2624432 , 0.97289717, 1.09735761, 1.28426082,        nan,
              nan,        nan])

In [22]:
np.exp(arr)

array([4.92223563, 2.57674995, 3.33406981, 5.20347077,        nan,
              nan,        nan])

In [23]:
np.log(arr)

array([ 0.46609778, -0.05495378,  0.18581023,  0.50036663,         nan,
               nan,         nan])

In [25]:
np.log10(arr)

array([ 0.20242369, -0.02386612,  0.08069636,  0.21730647,         nan,
               nan,         nan])

In [26]:
np.log1p(arr)

array([0.95310965, 0.66604773, 0.79036178, 0.97430521,        nan,
              nan,        nan])

In [27]:
np.sign(arr)

array([ 1.,  1.,  1.,  1., nan, nan, nan])

In [28]:
np.ceil(arr)

array([ 2.,  1.,  2.,  2., nan, nan, nan])

In [29]:
np.floor(arr)

array([ 1.,  0.,  1.,  1., nan, nan, nan])

In [30]:
np.rint(arr)

array([ 2.,  1.,  1.,  2., nan, nan, nan])

In [31]:
np.modf(arr)

(array([0.59376282, 0.94652889, 0.20419372, 0.64932586,        nan,
               nan,        nan]),
 array([ 1.,  0.,  1.,  1., nan, nan, nan]))

In [32]:
np.isnan(arr)

array([False, False, False, False,  True,  True,  True])

In [33]:
np.isfinite(arr)

array([ True,  True,  True,  True, False, False, False])

In [34]:
np.isinf(arr)

array([False, False, False, False, False, False, False])

In [37]:
np.cos(arr)

array([-0.02296448,  0.58450303,  0.35844586, -0.07844884,         nan,
               nan,         nan])

In [38]:
np.cosh(arr)

array([2.56269767, 1.48241786, 1.81700177, 2.69782509,        nan,
              nan,        nan])

In [39]:
np.sin(arr)

array([0.99973628, 0.81139153, 0.93355051, 0.99691814,        nan,
              nan,        nan])

In [40]:
np.sinh(arr)

array([2.35953796, 1.09433209, 1.51706804, 2.50564567,        nan,
              nan,        nan])

In [41]:
np.tan(arr)

array([-43.53402951,   1.38817334,   2.60443935, -12.70787572,
                nan,          nan,          nan])

In [42]:
np.tanh(arr)

array([0.92072427, 0.73820757, 0.83492931, 0.92876506,        nan,
              nan,        nan])

In [43]:
np.arccos(arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\3874515196.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([       nan, 0.32849519,        nan,        nan,        nan,
              nan,        nan])

In [44]:
np.arccosh(arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\1429270968.py:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(arr)


array([1.04195812,        nan, 0.62864899, 1.08549959,        nan,
              nan,        nan])

In [45]:
np.arcsin(arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\1580827672.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr)


array([       nan, 1.24230113,        nan,        nan,        nan,
              nan,        nan])

In [46]:
np.arcsinh(arr)

array([1.24567299, 0.84305397, 1.01865512, 1.27483962,        nan,
              nan,        nan])

In [47]:
np.arctan(arr)

array([1.01044007, 0.75793509, 0.87777325, 1.02575126,        nan,
              nan,        nan])

In [48]:
np.arctanh(arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\2021640537.py:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(arr)


array([      nan, 1.7973308,       nan,       nan,       nan,       nan,
             nan])

In [49]:
np.logical_not(arr)

array([False, False, False, False, False, False, False])

<h3>2:</h3>

add(x, y): возвращает сумму x и y.

subtract(x, y): возвращает разность x и y.

multiply(x, y): возвращает произведение x и y.

divide(x, y): возвращает частное от деления x на y.

floor_divide(x, y): возвращает частное от деления x на y, округленное до ближайшего меньшего целого.

power(x, y): возвращает x в степени y.

maximum(x, y): возвращает максимальное значение из x и y.

fmax(x, y): возвращает максимальное значение из x и y, где NaN игнорируется.

minimum(x, y): возвращает минимальное значение из x и y.

fmin(x, y): возвращает минимальное значение из x и y, где NaN игнорируется.

mod(x, y): возвращает остаток от деления x на y.

copysign(x, y): возвращает число с абсолютным значением из x и знаком из y.

greater(x, y): возвращает True, если x больше, чем y.

greater_equal(x, y): возвращает True, если x больше или равно y.

less(x, y): возвращает True, если x меньше, чем y.

less_equal(x, y): возвращает True, если x меньше или равно y.

equal(x, y): возвращает True, если x равно y.

not_equal(x, y): возвращает True, если x не равно y.

logical_and(x, y): возвращает логическое "И" для соответствующих элементов массивов.

logical_or(x, y): возвращает логическое "ИЛИ" для соответствующих элементов массивов.

logical_xor(x, y): возвращает логическое "исключающее ИЛИ" для соответствующих элементов массивов.

In [51]:
np.add(arr, arr)

array([3.18752565, 1.89305779, 2.40838745, 3.29865172,        nan,
              nan,        nan])

In [52]:
np.subtract(arr, arr)

array([ 0.,  0.,  0.,  0., nan, nan, nan])

In [53]:
np.multiply(arr, arr)

array([2.54007994, 0.89591695, 1.45008253, 2.72027579,        nan,
              nan,        nan])

In [56]:
np.divide(arr, arr)

array([ 1.,  1.,  1.,  1., nan, nan, nan])

In [57]:
np.floor_divide(arr, arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\232722763.py:1: RuntimeWarning: invalid value encountered in floor_divide
  np.floor_divide(arr, arr)


array([ 1.,  1.,  1.,  1., nan, nan, nan])

In [58]:
np.power(arr, arr)

array([2.101916  , 0.9493143 , 1.25076019, 2.28249154,        nan,
              nan,        nan])

In [59]:
np.maximum(arr, arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [60]:
np.fmax(arr, arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [61]:
np.minimum(arr, arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [63]:
np.fmin(arr, arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [64]:
np.mod(arr, arr)

C:\Users\nikik\AppData\Local\Temp\ipykernel_2416\1813593803.py:1: RuntimeWarning: invalid value encountered in remainder
  np.mod(arr, arr)


array([ 0.,  0.,  0.,  0., nan, nan, nan])

In [66]:
np.copysign(arr,arr)

array([1.59376282, 0.94652889, 1.20419372, 1.64932586,        nan,
              nan,        nan])

In [67]:
np.greater(arr, arr)

array([False, False, False, False, False, False, False])

In [68]:
np.greater_equal(arr, arr)

array([ True,  True,  True,  True, False, False, False])

In [69]:
np.less(arr,arr)

array([False, False, False, False, False, False, False])

In [70]:
np.less_equal(arr, arr)

array([ True,  True,  True,  True, False, False, False])

In [71]:
np.equal(arr,arr)

array([ True,  True,  True,  True, False, False, False])

In [72]:
np.not_equal(arr, arr)

array([False, False, False, False,  True,  True,  True])

In [73]:
np.logical_and(arr, arr)

array([ True,  True,  True,  True,  True,  True,  True])

In [74]:
np.logical_or(arr, arr)

array([ True,  True,  True,  True,  True,  True,  True])

In [75]:
np.logical_xor(arr, arr)

array([False, False, False, False, False, False, False])

<h2>Программирование с помощью массивов</h2>

In [76]:
import numpy as np

xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

In [81]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [79]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [82]:
import numpy as np

arr = np.random.randn(4,4)
arr

array([[ 1.58043019,  0.61189199, -0.61541542,  0.510631  ],
       [ 0.68635141, -0.2478695 , -0.24855384,  0.29052013],
       [ 1.03450827, -0.64968703,  0.85718114, -1.26962075],
       [ 0.48346356, -0.15436411,  0.07697315,  0.76521164]])

In [83]:
arr > 0

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True]])

In [85]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2,  2],
       [ 2, -2, -2,  2],
       [ 2, -2,  2, -2],
       [ 2, -2,  2,  2]])

In [86]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -0.61541542,  2.        ],
       [ 2.        , -0.2478695 , -0.24855384,  2.        ],
       [ 2.        , -0.64968703,  2.        , -1.26962075],
       [ 2.        , -0.15436411,  2.        ,  2.        ]])

<h2>Математическое и статическое операции</h2>

In [87]:
import numpy as np

arr = np.random.randn(5, 4)
arr

array([[ 0.84454447, -0.31598925,  0.65815446,  1.95138934],
       [-1.05774996,  0.25939957,  0.91620177,  1.62301105],
       [-0.39358207,  1.21125296,  1.50349992,  0.63943745],
       [ 0.51759895, -0.68899393,  0.39536137, -0.56289681],
       [-0.51605162, -1.19697048, -0.30681969, -0.96957455]])

In [88]:
arr.mean()

0.22556114699998053

In [90]:
np.mean(arr)

0.22556114699998053

In [91]:
arr.sum()

4.511222939999611

In [92]:
arr.mean(axis=1)

array([ 0.78452475,  0.43521561,  0.74015206, -0.08473261, -0.74735409])

In [93]:
arr.sum(axis=0)

array([-0.60524024, -0.73130114,  3.16639783,  2.68136648])

In [96]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [99]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [103]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

<h2>Задание 2:</h2>

sum(arr): возвращает сумму всех элементов в массиве arr.

mean(arr): возвращает среднее значение всех элементов в массиве arr.

std(arr): возвращает стандартное отклонение элементов в массиве arr.

var(arr): возвращает дисперсию элементов в массиве arr.

min(arr): возвращает минимальное значение из всех элементов в массиве arr.

max(arr): возвращает максимальное значение из всех элементов в массиве arr.

argmin(arr): возвращает индекс минимального значения в массиве arr.

argmax(arr): возвращает индекс максимального значения в массиве arr.

cumsum(arr): возвращает массив, содержащий накопленную сумму элементов в массиве arr.

cumprod(arr): возвращает массив, содержащий накопленное произведение элементов в массиве arr.

In [104]:
arr.sum()

45

In [105]:
arr.mean()

5.0

In [106]:
arr.std()

2.581988897471611

In [107]:
arr.var()

6.666666666666667

In [108]:
arr.min()

1

In [109]:
arr.max()

9

In [110]:
arr.argmax()

8

In [113]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [114]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

<h2>Методы булевых массивов</h2>

In [116]:
import numpy as np

arr = np.random.randn(100)
(arr > 0).sum()

46

In [117]:
import numpy as np

bools = np.array([False, False, True, False])
bools.any()

True

In [118]:
bools.all()

False

<h2>Сортировка</h2>

In [128]:
import numpy as np

arr = np.random.randn(6)
arr

array([-1.56604265, -0.53254277,  0.07599085,  0.66384334, -1.99107889,
        0.11521105])

In [129]:
arr.sort()
arr

array([-1.99107889, -1.56604265, -0.53254277,  0.07599085,  0.11521105,
        0.66384334])

In [130]:
import numpy as np

arr = np.random.randn(5,3)
arr

array([[-0.96777275,  0.15131589, -0.30733315],
       [ 0.59971337,  1.9755904 , -1.23544483],
       [-1.9838321 ,  1.09233444, -1.46092092],
       [ 0.30089686,  0.0234675 ,  1.09291558],
       [ 0.52419216, -1.86730263, -0.44835689]])

In [132]:
arr.sort(1)
arr

array([[-0.96777275, -0.30733315,  0.15131589],
       [-1.23544483,  0.59971337,  1.9755904 ],
       [-1.9838321 , -1.46092092,  1.09233444],
       [ 0.0234675 ,  0.30089686,  1.09291558],
       [-1.86730263, -0.44835689,  0.52419216]])

In [135]:
import numpy as np

large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

-1.699259126141734

<h2>Удаление дубликатов и другие теоретико-множественные операции</h2>

In [136]:
import numpy as np 

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [140]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [141]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [142]:
import numpy as np

values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

<h2>Задание 3:</h2>

unique(x): возвращает отсортированный уникальный массив значений из массива x.

intersect1d(x, y): возвращает отсортированный массив значений, которые есть в обоих массивах x и y.

union1d(x, y): возвращает отсортированный уникальный массив значений, которые есть в массивах x или y.

in1d(x, y): возвращает булев массив той же длины, что и массив x, указывающий, содержится ли каждый элемент из x в массиве y.

setdiff1d(x, y): возвращает отсортированный массив значений, которые есть в массиве x, но отсутствуют в массиве y.

setxor1d(x, y): возвращает отсортированный уникальный массив значений, которые есть только в одном из массивов x или y.

In [146]:
import numpy as np
ints = np.array([0,0,0,23,45,90,90])
np.unique(ints)

array([ 0, 23, 45, 90])

In [147]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [148]:
np.union1d([1,3,4,3],[3,1,2,1])

array([1, 2, 3, 4])

In [149]:
np.in1d([1,3,4,3],[3,1,2,1])

array([ True,  True, False,  True])

In [150]:
np.setdiff1d([1,3,4,3],[3,1,2,1])

array([4])

In [151]:
np.setxor1d([1,3,4,3],[3,1,2,1])

array([2, 4])

<h2>Файловый ввод-вывод массивов</h2>

In [153]:
import numpy as np

arr = np.arange(10)
np.save('some_array', arr)

In [154]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.savez('array_archive.npz', a=arr, b=arr)

In [156]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

<h2>Линейная алгебра</h2>

In [158]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [159]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [160]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [161]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [163]:
x @ np.ones(3)

array([ 6., 15.])

In [164]:
from numpy.linalg import inv, qr

X = np.random.randn(5,5)
mat = X.T.dot(X)
inv(mat)

array([[ 0.26221083,  0.07325905,  0.07558841,  0.09002644,  0.03450188],
       [ 0.07325905,  0.16293892, -0.06285806,  0.05432396,  0.10085009],
       [ 0.07558841, -0.06285806,  0.56131368, -0.32869269, -0.21908421],
       [ 0.09002644,  0.05432396, -0.32869269,  0.95008529,  0.70358179],
       [ 0.03450188,  0.10085009, -0.21908421,  0.70358179,  0.69739655]])

In [165]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  6.87596404e-17, -1.62268499e-18,
        -1.28697133e-16, -8.58733598e-17],
       [ 6.90370512e-17,  1.00000000e+00,  8.43541619e-17,
         1.51019983e-16,  1.08937216e-16],
       [-2.87986269e-17, -4.26952153e-17,  1.00000000e+00,
         1.29844746e-16,  2.44627872e-17],
       [-2.24354114e-17, -8.74118947e-17,  8.86950482e-17,
         1.00000000e+00,  4.79258722e-16],
       [ 1.07313601e-16,  5.24699558e-17,  1.98910447e-16,
         2.03512516e-17,  1.00000000e+00]])

In [166]:
q,r = qr(mat)
r

array([[-9.24768212, 11.81385623,  4.68893337,  9.40851969, -9.73450373],
       [ 0.        , -6.27343992, -0.65424613, -2.14799438,  3.08924326],
       [ 0.        ,  0.        , -2.28301684, -2.23219577,  1.53856862],
       [ 0.        ,  0.        ,  0.        , -4.99882709,  5.95457827],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.9802281 ]])

<h2>Генерация псевдо-случайных чисел</h2>

In [167]:
import numpy as np

samples = np.random.normal(size=(4,4))
samples

array([[-0.29051579,  0.40344793,  1.40906339,  0.70851839],
       [ 1.06715559,  0.65786767, -0.30911099,  0.0591509 ],
       [-0.14307499, -0.49230694, -0.39586578,  0.32704526],
       [-0.55138173,  0.1668844 ,  0.74463779,  1.16024432]])

In [169]:
from random import normalvariate
 
N = 1000000
%timeit samples = [normalvariate(0,1) for _ in range(N)]

1.31 s ± 33.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [170]:
%timeit np.random.normal(size=N)

46.7 ms ± 5.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [171]:
np.random.seed(1234)

In [172]:
import numpy as np

rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])